"""
media.py
========
Real demonstration photos for the exercise library, served from the
public-domain free-exercise-db project (github.com/yuhonas/free-exercise-db).
Each mapped exercise gets its start + finish position photos; unmapped
(rehab-specific) exercises keep the built-in illustration.
"""

PHOTO_BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises"

# our exercise id -> list of photo paths (start / finish position)
PHOTOS = {
    "abductor_machine": ["Thigh_Abductor/0.jpg", "Thigh_Abductor/1.jpg"],
    "adductor_machine": ["Thigh_Adductor/0.jpg", "Thigh_Adductor/1.jpg"],
    "assess_plank": ["Plank/0.jpg", "Plank/1.jpg"],
    "back_extension_45": ["Hyperextensions_Back_Extensions/0.jpg", "Hyperextensions_Back_Extensions/1.jpg"],
    "band_er": ["External_Rotation_with_Band/0.jpg", "External_Rotation_with_Band/1.jpg"],
    "band_er_90": ["External_Rotation/0.jpg", "External_Rotation/1.jpg"],
    "band_ir": ["Internal_Rotation_with_Band/0.jpg", "Internal_Rotation_with_Band/1.jpg"],
    "band_pull_apart": ["Band_Pull_Apart/0.jpg", "Band_Pull_Apart/1.jpg"],
    "barbell_hip_thrust": ["Barbell_Hip_Thrust/0.jpg", "Barbell_Hip_Thrust/1.jpg"],
    "barbell_rdl": ["Romanian_Deadlift/0.jpg", "Romanian_Deadlift/1.jpg"],
    "barbell_row": ["Bent_Over_Barbell_Row/0.jpg", "Bent_Over_Barbell_Row/1.jpg"],
    "bike_intervals": ["Bicycling_Stationary/0.jpg", "Bicycling_Stationary/1.jpg"],
    "bike_tempo": ["Bicycling_Stationary/0.jpg", "Bicycling_Stationary/1.jpg"],
    "bike_warmup": ["Bicycling_Stationary/0.jpg", "Bicycling_Stationary/1.jpg"],
    "box_jump": ["Front_Box_Jump/0.jpg", "Front_Box_Jump/1.jpg"],
    "box_squat": ["Box_Squat/0.jpg", "Box_Squat/1.jpg"],
    "cable_er": ["External_Rotation_with_Cable/0.jpg", "External_Rotation_with_Cable/1.jpg"],
    "cable_face_pull": ["Face_Pull/0.jpg", "Face_Pull/1.jpg"],
    "cable_pallof": ["Pallof_Press/0.jpg", "Pallof_Press/1.jpg"],
    "calf_raise_double": ["Standing_Dumbbell_Calf_Raise/0.jpg", "Standing_Dumbbell_Calf_Raise/1.jpg"],
    "calf_raise_single": ["Standing_Dumbbell_Calf_Raise/0.jpg", "Standing_Dumbbell_Calf_Raise/1.jpg"],
    "cardio_warmup_20": ["Bicycling_Stationary/0.jpg", "Bicycling_Stationary/1.jpg"],
    "cat_cow": ["Cat_Stretch/0.jpg", "Cat_Stretch/1.jpg"],
    "chest_press_machine": ["Machine_Bench_Press/0.jpg", "Machine_Bench_Press/1.jpg"],
    "chest_supported_row": ["Dumbbell_Incline_Row/0.jpg", "Dumbbell_Incline_Row/1.jpg"],
    "cross_body_stretch": ["Shoulder_Stretch/0.jpg", "Shoulder_Stretch/1.jpg"],
    "db_bench": ["Dumbbell_Bench_Press_with_Neutral_Grip/0.jpg", "Dumbbell_Bench_Press_with_Neutral_Grip/1.jpg"],
    "db_curl": ["Dumbbell_Alternate_Bicep_Curl/0.jpg", "Dumbbell_Alternate_Bicep_Curl/1.jpg"],
    "db_row": ["One-Arm_Dumbbell_Row/0.jpg", "One-Arm_Dumbbell_Row/1.jpg"],
    "db_shoulder_press": ["Dumbbell_Shoulder_Press/0.jpg", "Dumbbell_Shoulder_Press/1.jpg"],
    "db_shrug": ["Dumbbell_Shrug/0.jpg", "Dumbbell_Shrug/1.jpg"],
    "deadbug": ["Dead_Bug/0.jpg", "Dead_Bug/1.jpg"],
    "eccentric_calf": ["Standing_Calf_Raises/0.jpg", "Standing_Calf_Raises/1.jpg"],
    "face_pull": ["Face_Pull/0.jpg", "Face_Pull/1.jpg"],
    "farmer_carry": ["Farmers_Walk/0.jpg", "Farmers_Walk/1.jpg"],
    "floor_press": ["Dumbbell_Floor_Press/0.jpg", "Dumbbell_Floor_Press/1.jpg"],
    "foam_roll_quads": ["Quadriceps-SMR/0.jpg", "Quadriceps-SMR/1.jpg"],
    "front_squat": ["Front_Barbell_Squat/0.jpg", "Front_Barbell_Squat/1.jpg"],
    "glute_bridge": ["Butt_Lift_Bridge/0.jpg", "Butt_Lift_Bridge/1.jpg"],
    "goblet_squat": ["Goblet_Squat/0.jpg", "Goblet_Squat/1.jpg"],
    "hack_squat": ["Hack_Squat/0.jpg", "Hack_Squat/1.jpg"],
    "hip_thrust": ["Barbell_Hip_Thrust/0.jpg", "Barbell_Hip_Thrust/1.jpg"],
    "incline_db_press": ["Incline_Dumbbell_Bench_With_Palms_Facing_In/0.jpg", "Incline_Dumbbell_Bench_With_Palms_Facing_In/1.jpg"],
    "incline_pushup": ["Incline_Push-Up/0.jpg", "Incline_Push-Up/1.jpg"],
    "incline_walk": ["Walking_Treadmill/0.jpg", "Walking_Treadmill/1.jpg"],
    "lat_pulldown_machine": ["Full_Range-Of-Motion_Lat_Pulldown/0.jpg", "Full_Range-Of-Motion_Lat_Pulldown/1.jpg"],
    "lateral_raise": ["Side_Lateral_Raise/0.jpg", "Side_Lateral_Raise/1.jpg"],
    "leg_curl_machine": ["Seated_Leg_Curl/0.jpg", "Seated_Leg_Curl/1.jpg"],
    "leg_extension": ["Leg_Extensions/0.jpg", "Leg_Extensions/1.jpg"],
    "leg_press": ["Leg_Press/0.jpg", "Leg_Press/1.jpg"],
    "monster_walk": ["Monster_Walk/0.jpg", "Monster_Walk/1.jpg"],
    "nordic_curl": ["Natural_Glute_Ham_Raise/0.jpg", "Natural_Glute_Ham_Raise/1.jpg"],
    "pallof_press": ["Pallof_Press/0.jpg", "Pallof_Press/1.jpg"],
    "pec_deck": ["Butterfly/0.jpg", "Butterfly/1.jpg"],
    "plank": ["Plank/0.jpg", "Plank/1.jpg"],
    "plank_tap": ["Plank/0.jpg", "Plank/1.jpg"],
    "pullup": ["Pullups/0.jpg", "Pullups/1.jpg"],
    "pushup": ["Pushups/0.jpg", "Pushups/1.jpg"],
    "rear_delt_fly": ["Reverse_Machine_Flyes/0.jpg", "Reverse_Machine_Flyes/1.jpg"],
    "reverse_lunge": ["Dumbbell_Rear_Lunge/0.jpg", "Dumbbell_Rear_Lunge/1.jpg"],
    "rfe_split_squat": ["Split_Squat_with_Dumbbells/0.jpg", "Split_Squat_with_Dumbbells/1.jpg"],
    "romanian_deadlift": ["Romanian_Deadlift/0.jpg", "Romanian_Deadlift/1.jpg"],
    "scaption_raise": ["Front_Two-Dumbbell_Raise/0.jpg", "Front_Two-Dumbbell_Raise/1.jpg"],
    "seated_cable_row": ["Seated_Cable_Rows/0.jpg", "Seated_Cable_Rows/1.jpg"],
    "seated_calf_machine": ["Seated_Calf_Raise/0.jpg", "Seated_Calf_Raise/1.jpg"],
    "shadow_footwork": ["Carioca_Quick_Step/0.jpg", "Carioca_Quick_Step/1.jpg"],
    "side_leg_raise": ["Side_Leg_Raises/0.jpg", "Side_Leg_Raises/1.jpg"],
    "side_plank": ["Side_Bridge/0.jpg", "Side_Bridge/1.jpg"],
    "side_plank_leglift": ["Side_Bridge/0.jpg", "Side_Bridge/1.jpg"],
    "single_leg_bridge": ["Single_Leg_Glute_Bridge/0.jpg", "Single_Leg_Glute_Bridge/1.jpg"],
    "single_leg_press": ["Leg_Press/0.jpg", "Leg_Press/1.jpg"],
    "single_leg_rdl": ["Kettlebell_One-Legged_Deadlift/0.jpg", "Kettlebell_One-Legged_Deadlift/1.jpg"],
    "skater_bound": ["Lateral_Bound/0.jpg", "Lateral_Bound/1.jpg"],
    "slider_curl": ["Platform_Hamstring_Slides/0.jpg", "Platform_Hamstring_Slides/1.jpg"],
    "smith_calf": ["Smith_Machine_Calf_Raise/0.jpg", "Smith_Machine_Calf_Raise/1.jpg"],
    "soleus_raise": ["Seated_Calf_Raise/0.jpg", "Seated_Calf_Raise/1.jpg"],
    "split_squat": ["Split_Squats/0.jpg", "Split_Squats/1.jpg"],
    "sprint_strides": ["Wind_Sprints/0.jpg", "Wind_Sprints/1.jpg"],
    "step_up": ["Dumbbell_Step_Ups/0.jpg", "Dumbbell_Step_Ups/1.jpg"],
    "stretch_calf": ["Calf_Stretch_Hands_Against_Wall/0.jpg", "Calf_Stretch_Hands_Against_Wall/1.jpg"],
    "stretch_chest": ["Chest_And_Front_Of_Shoulder_Stretch/0.jpg", "Chest_And_Front_Of_Shoulder_Stretch/1.jpg"],
    "stretch_glute": ["IT_Band_and_Glute_Stretch/0.jpg", "IT_Band_and_Glute_Stretch/1.jpg"],
    "stretch_hamstring": ["Standing_Hamstring_and_Calf_Stretch/0.jpg", "Standing_Hamstring_and_Calf_Stretch/1.jpg"],
    "stretch_hip_flexor": ["Kneeling_Hip_Flexor/0.jpg", "Kneeling_Hip_Flexor/1.jpg"],
    "stretch_quad": ["Standing_Elevated_Quad_Stretch/0.jpg", "Standing_Elevated_Quad_Stretch/1.jpg"],
    "tempo_goblet_squat": ["Goblet_Squat/0.jpg", "Goblet_Squat/1.jpg"],
    "trap_bar_deadlift": ["Trap_Bar_Deadlift/0.jpg", "Trap_Bar_Deadlift/1.jpg"],
    "triceps_pushdown": ["Triceps_Pushdown_-_Rope_Attachment/0.jpg", "Triceps_Pushdown_-_Rope_Attachment/1.jpg"],
    "walking_lunge": ["Dumbbell_Lunges/0.jpg", "Dumbbell_Lunges/1.jpg"],
    "worlds_greatest": ["Worlds_Greatest_Stretch/0.jpg", "Worlds_Greatest_Stretch/1.jpg"],
}


def get_photos(ex_id: str) -> list:
    """Full photo URLs for an exercise id ([] when no real photos exist)."""
    return [f"{PHOTO_BASE}/{p}" for p in PHOTOS.get(ex_id, [])]
